// All study content. Quotes are from the JH11-21 source book pages on the demo.
// "Polster" lines are from Dr. Polster's classes (Sept 22, 25, 29).

const DEMO_DATE = "2026-10-02T08:30:00-04:00";
const AI_URL = "https://jh-demo-ai.vercel.app/api/chat";
const AI_DAILY_LIMIT = 12;

const SPEAKERS = {
  heine: { name: "Heine", full: "Heinrich Heine", topic: "conversion", img: "img/heine.jpg", page: "p. 13",
    tag: "Converted for a career. Baptism = ticket into European culture." },
  mendelssohn: { name: "Mendelssohn", full: "Abraham Mendelssohn", topic: "conversion", img: "img/mendelssohn.jpg", page: "pp. 11-12",
    tag: "Raised his kids Christian: the creed of the most civilized people." },
  jacobson: { name: "Jacobson", full: "Israel Jacobson", topic: "beginnings", img: "img/jacobson.jpg", page: "p. 14",
    tag: "First Reform 'Temple' (1810). Goal: religious education." },
  hamburg: { name: "Hamburg Temple", full: "Hamburg Temple Constitution", topic: "beginnings", img: "img/temple-illustration.jpg", page: "p. 15",
    tag: "Worship neglected, so: German sermon, organ, choir, confirmation." },
  frankel: { name: "Frankel", full: "Zecharias Frankel", topic: "issues", img: "img/frankel.jpg", page: "pp. 17-18",
    tag: "Team Hebrew. Conserve what is sacred. Founder of Conservative." },
  geiger: { name: "Geiger", full: "Abraham Geiger", topic: "issues", img: "img/geiger.jpg", page: "pp. 18, 22-23",
    tag: "Team German. Judaism is a religion, not a nation." },
  pittsburgh: { name: "Pittsburgh Platform", full: "Pittsburgh Platform (1885)", topic: "evolution", img: "img/wise.jpg", page: "pp. 24-25",
    tag: "Classical Reform: no longer a nation, no return to Palestine." },
  columbus: { name: "Columbus Platform", full: "Columbus Platform (1937)", topic: "evolution", img: null, badge: "1937", page: "pp. 26-28",
    tag: "After Nazi laws: Jewish people again, support a homeland, Hebrew back." },
};

const TOPICS = {
  conversion: "Conversion",
  beginnings: "Reform: Beginnings",
  issues: "Reform: Main Issues",
  evolution: "Reform: Evolution",
};

// star = Dr. Polster flagged it in class
const QUOTES = [
  // Heine
  { id: "h1", who: "heine", star: true, text: "The baptismal certificate is the ticket of admission to European culture.",
    clue: "Baptism = a ticket in. Conversion as a social move." },
  { id: "h2", who: "heine", text: "From the nature of my thinking you can deduce that baptism is a matter of indifference to me.",
    clue: "Baptism means nothing religious to him." },
  { id: "h3", who: "heine", text: "For me perhaps its significance will be that I can better devote myself to championing the rights of my unfortunate brethren.",
    clue: "Converting so he can fight for Jews from the inside." },
  { id: "h4", who: "heine", text: "I hold it beneath my dignity and a stain on my honor to undergo conversion in order to obtain a position in Prussia.",
    clue: "Ashamed to convert just for a job in Prussia." },
  { id: "h5", who: "heine", text: "I'll turn Catholic yet for spite, and hang myself.",
    clue: "Bitter joke about converting." },
  { id: "h6", who: "heine", text: "I make no secret of my Judaism, to which I have not returned, because I never left it.",
    clue: "Later in life he kept his Jewishness." },
  { id: "h7", who: "heine", text: "Where they burn books, they ultimately burn people.",
    clue: "From his play. Dr. Polster said to note it (comes back with the Nazis)." },
  // Mendelssohn
  { id: "m1", who: "mendelssohn", star: true, text: "We have educated you and your brothers and sister in the Christian faith, because it is the creed of most civilized people.",
    clue: "Letter to his daughter. Christianity = religion of the civilized." },
  { id: "m2", who: "mendelssohn", star: true, text: "Some thousands of years ago the Jewish form was the reigning one, then the heathen form, and now it is the Christian.",
    clue: "Judaism 'had its day'. Now it's Christianity's time." },
  { id: "m3", who: "mendelssohn", text: "The outward form of religion your teacher has given you is historical, and changeable like all human ordinances.",
    clue: "Religion's outer form changes over time." },
  { id: "m4", who: "mendelssohn", text: "I know it, I believe it, I live in this faith, and this is my religion.",
    clue: "His religion = conscience and being good, not Judaism." },
  { id: "m5", who: "mendelssohn", text: "By pronouncing your confession of faith you have fulfilled the claims of society on you, and obtained the name of a Christian.",
    clue: "Speaking to his daughter Fanny at her confirmation." },
  { id: "m6", who: "mendelssohn", text: "Because it is the religious form acceptable to the majority of civilized human beings.",
    clue: "Why he and his wife became Christian." },
  // Jacobson
  { id: "j1", who: "jacobson", star: true, text: "What I had in mind when I first thought about building this temple was your religious education.",
    clue: "Opening line of his dedication speech (first 4 lines of p. 14)." },
  { id: "j2", who: "jacobson", star: true, text: "Be it far from me that I should have any secret intention to undermine the pillars of your faith.",
    clue: "Not trying to destroy Judaism." },
  { id: "j3", who: "jacobson", star: true, text: "On all sides, enlightenment opens up new areas for development. Why should we alone remain behind?",
    clue: "Everyone is progressing, so should we." },
  { id: "j4", who: "jacobson", text: "Who would dare to deny that our service is sickly because of many useless things, that in part it has degenerated into a thoughtless recitation of prayers and formulas.",
    clue: "Old services felt like empty formulas." },
  { id: "j5", who: "jacobson", text: "If I do seek here first some rapprochement between you and our Christian neighbors, I would ask more for your gratitude and honest help than for your criticism.",
    clue: "Bringing Jews and Christians closer." },
  // Hamburg
  { id: "t1", who: "hamburg", star: true, text: "Since public worship has for some time been neglected by so many, because of the ever decreasing knowledge of the language in which alone it has until now been conducted...",
    clue: "First lines of the constitution: nobody understands Hebrew anymore." },
  { id: "t2", who: "hamburg", text: "Specifically, there shall be introduced at such services a German sermon, and choral singing to the accompaniment of an organ.",
    clue: "New things added to worship." },
  { id: "t3", who: "hamburg", text: "The children of both sexes, after having received adequate schooling in the teachings of the faith, shall be accepted as confirmants of the Mosaic religion.",
    clue: "Confirmation for boys AND girls." },
  { id: "t4", who: "hamburg", text: "Convinced of the necessity to restore public worship to its deserving dignity and importance.",
    clue: "Make worship dignified again." },
  { id: "t5", who: "hamburg", text: "By adopting the designation traditionally reserved for the fallen Temple of Jerusalem, the Reformers symbolically relinquished the hope of Israel's restoration and declared Hamburg their Jerusalem.",
    clue: "Footnote: why they called it a 'Temple'." },
  // Frankel
  { id: "f1", who: "frankel", star: true, text: "Now it is necessary to conserve the things which are truly sacred to the entire people, to prevent any schism in Israel.",
    clue: "CONSERVE = Conservative movement. Keep Hebrew so Jews don't split." },
  { id: "f2", who: "frankel", text: "In order to understand Judaism in the present one must look back and investigate its past.",
    clue: "Positive-historical Judaism." },
  { id: "f3", who: "frankel", text: "The positive forms of Judaism are deeply rooted within its innermost being and must not be discarded coldly and heartlessly.",
    clue: "Don't throw tradition away." },
  { id: "f4", who: "frankel", text: "The Zeitgeist is as fickle as the times. Besides, it is cold.",
    clue: "Don't just follow the spirit of the times." },
  { id: "f5", who: "frankel", text: "Rather than creating new parties, we must make peace between the existing ones.",
    clue: "Unity. Don't split the people." },
  { id: "f6", who: "frankel", text: "It is the pride of Judaism that no person, and no social class, may presume authority, but that every decision must evolve organically from principles.",
    clue: "Decisions need principles." },
  // Geiger
  { id: "g1", who: "geiger", star: true, text: "A German prayer strikes a deeper chord than a Hebrew prayer.",
    clue: "You understand German, so it means more." },
  { id: "g2", who: "geiger", star: true, text: "No member of this conference would wish to link Judaism to a particular nation.",
    clue: "Judaism = religion, not a nation (p. 18, right column)." },
  { id: "g3", who: "geiger", star: true, text: "Consequently, the national aspect of Israel must recede into the background.",
    clue: "Preface to his prayer book. Dr. Polster: commit it to memory!" },
  { id: "g4", who: "geiger", text: "Anyone who imagines Judaism to be walking on the crutches of a language deeply offends it.",
    clue: "Judaism doesn't need Hebrew to stand." },
  { id: "g5", who: "geiger", text: "The Hebrew language has ceased to be alive for the people.",
    clue: "Nobody really speaks Hebrew anymore." },
  { id: "g6", who: "geiger", text: "Wholly faded from our consciousness is the belief in the restoration of a Jewish State in Palestine.",
    clue: "Prayer book preface: no more praying for Zion." },
  { id: "g7", who: "geiger", text: "The look into the future should arouse the happy hope in the unification of all mankind, in truth, in justice, and in peace.",
    clue: "Universalism." },
  { id: "g8", who: "geiger", text: "The separation between Israel and the other peoples, which existed at one time, has no right to be expressed in prayer.",
    clue: "Don't pray about being separate." },
  // Pittsburgh
  { id: "p1", who: "pittsburgh", star: true, text: "We consider ourselves no longer a nation, but a religious community, and therefore expect neither a return to Palestine, nor a sacrificial worship under the sons of Aaron.",
    clue: "Fifth principle. Classical Reform." },
  { id: "p2", who: "pittsburgh", text: "All such Mosaic and rabbinical laws as regulate diet, priestly purity, and dress ... fail to impress the modern Jew with a spirit of priestly holiness.",
    clue: "Fourth principle: drop kashrut and dress rules." },
  { id: "p3", who: "pittsburgh", text: "Today we accept as binding only the moral laws, and maintain only such ceremonies as elevate and sanctify our lives.",
    clue: "Third principle: only moral laws are binding." },
  { id: "p4", who: "pittsburgh", text: "We recognize in Judaism a progressive religion, ever striving to be in accord with the postulates of reason.",
    clue: "Sixth principle: religion + reason." },
  { id: "p5", who: "pittsburgh", text: "We recognize in every religion an attempt to grasp the Infinite.",
    clue: "First principle: all religions have truth." },
  { id: "p6", who: "pittsburgh", text: "We reject as ideas not rooted in Judaism the beliefs both in bodily resurrection and in Gehenna and Eden.",
    clue: "Seventh principle: no hell and paradise." },
  // Columbus
  { id: "c1", who: "columbus", star: true, text: "Judaism is the soul of which Israel is the body.",
    clue: "Jewish people (Israel) matter again." },
  { id: "c2", who: "columbus", star: true, text: "We affirm the obligation of all Jewry to aid in its upbuilding as a Jewish homeland.",
    clue: "Support a homeland in Palestine. Opposite of 1885." },
  { id: "c3", who: "columbus", text: "The use of Hebrew, together with the vernacular, in our worship and instruction.",
    clue: "Hebrew comes back." },
  { id: "c4", who: "columbus", text: "The preservation of the Sabbath, festivals and Holy Days, the retention and development of such customs, symbols and ceremonies as possess inspirational value.",
    clue: "Bring back meaningful customs." },
  { id: "c5", who: "columbus", text: "Judaism is the historical religious experience of the Jewish people.",
    clue: "Peoplehood is back." },
  { id: "c6", who: "columbus", text: "It presents them not as a fixed creed but as a guide for the progressive elements of Jewry.",
    clue: "Guide, not fixed rules." },
  { id: "c7", who: "columbus", text: "Not only a haven of refuge for the oppressed but also a center of Jewish culture and spiritual life.",
    clue: "What Palestine should be (1937, Nazi era)." },
];

// Dr. Polster's own lines from class
const POLSTER = [
  { text: "It's not memorizing the quote. It's understanding who's associated with that particular quote.", about: "How the demo works" },
  { text: "Highlight that, underline it, circle it, commit it to memory. It's on the demo on Friday. Period.", about: "Geiger: \"the national aspect of Israel must recede into the background\"" },
  { text: "Don't look at the other stuff. It's just on that stuff.", about: "Demo scope" },
  { text: "Dates don't matter to me.", about: "No dates on the demo (unless he says so)" },
  { text: "It wasn't a religious move. It was a political move. Or a social move.", about: "Heine and Mendelssohn converting" },
  { text: "There's a big difference between conversion of choice and conversion out of fear.", about: "Then vs. the Inquisition and Crusades" },
  { text: "That's the OG of the Reform movement.", about: "Jacobson and the Hamburg Temple's intent" },
  { text: "We're here to stay. We're in Germany. This is our Beit HaMikdash.", about: "Why they called it a \"temple\"" },
  { text: "We have to conserve. We have to conserve.", about: "Frankel, founder of the Conservative movement" },
  { text: "Jews are a religion, Geiger says. We're not a people. We're not a nation.", about: "Geiger at Frankfurt" },
  { text: "Everybody should be like Mike.", about: "Reform wanting to look like their Christian neighbours" },
  { text: "Nobody leaves this room thinking that Reform Jews stand for anti-Israel. It's not true.", about: "Early Reform vs. Reform today" },
  { text: "You're going to look at the 3 questions and you're going to say, 'I don't like this one.' You're going to cross it out.", about: "Short answers: pick 2 of 3" },
  { text: "Hopefully you'll have the ability on a sit-down within 2 seconds to be able to identify that quote.", about: "Quote speed" },
];

// Multiple-choice facts. a = correct answer, w = wrong answers.
const FACTS = [
  { t: "conversion", q: "After emancipation, conversion to Christianity was mostly...", a: "A choice, made for social and political reasons", w: ["Forced, like in the Spanish Inquisition", "Because Jews believed in Jesus", "Banned by the government"] },
  { t: "conversion", q: "About how many Jews in east-central Europe converted in the 19th century?", a: "At least 250,000", w: ["About 2,500", "About 25 million", "Almost none"] },
  { t: "conversion", q: "Which born-Jewish convert became British prime minister?", a: "Benjamin Disraeli", w: ["Heinrich Heine", "Felix Mendelssohn", "Isaac M. Wise"] },
  { t: "conversion", q: "Why did Heine get baptized?", a: "To get a doctorate and a job as a civil servant or professor", w: ["Because he truly believed in Christianity", "To marry a Christian princess", "Because the Nazis forced him"] },
  { t: "conversion", q: "Did Heine's conversion get him the job he wanted?", a: "No. He never got the university position", w: ["Yes, he became a famous professor", "Yes, he became a judge in Prussia", "He never tried"] },
  { t: "conversion", q: "Who was Abraham Mendelssohn's father?", a: "Moses Mendelssohn, father of the Haskalah (Jewish Enlightenment)", w: ["Heinrich Heine", "Israel Jacobson", "Abraham Geiger"] },
  { t: "conversion", q: "Who did Abraham Mendelssohn write his famous letter to?", a: "His daughter (Fanny)", w: ["His rabbi", "The King of Prussia", "Heinrich Heine"] },
  { t: "conversion", q: "Mendelssohn's main reason for raising his kids Christian was...", a: "Christianity is the creed of the most civilized people today", w: ["He was afraid of being killed", "His rabbi told him to", "Christianity has better holidays"] },
  { t: "conversion", q: "How are Heine's and Mendelssohn's reasons alike?", a: "Both were social or political, not religious", w: ["Both truly believed in Jesus", "Both were forced", "Both wanted to move to Palestine"] },
  { t: "conversion", q: "Moses Mendelssohn translated the Torah into...", a: "German", w: ["English", "Yiddish only", "Latin"] },
  { t: "conversion", q: "Mendelssohn says religion's outward form is...", a: "Historical and changeable", w: ["Fixed forever", "Only for Jews", "Decided by kings"] },
  { t: "conversion", q: "'Ticket of admission' in Heine's quote means...", a: "Baptism is how a Jew gets let into European society", w: ["Buying a train ticket to Paris", "A ticket to a concert", "Going to synagogue"] },
  { t: "beginnings", q: "Israel Jacobson's job was...", a: "Not a rabbi (a layman / businessman)", w: ["Chief rabbi of Berlin", "A Christian priest", "A professor"] },
  { t: "beginnings", q: "What was new at Jacobson's temple opening?", a: "Christians attended, orchestra and choir, prayers in German and Hebrew", w: ["Only Hebrew and no music", "Women led every prayer", "It was held in Jerusalem"] },
  { t: "beginnings", q: "Jacobson said the purpose of his temple was...", a: "Religious education", w: ["To convert Jews to Christianity", "To raise money", "To prepare to move to Zion"] },
  { t: "beginnings", q: "Jacobson complained the old service was 'sickly' because it was...", a: "A thoughtless recitation of prayers and formulas", w: ["Too short", "In German", "Too modern"] },
  { t: "beginnings", q: "Why did the Hamburg Temple say worship was neglected?", a: "People knew less and less Hebrew, the only language of prayer", w: ["The building was too small", "The rabbi was sick", "Prayer was banned"] },
  { t: "beginnings", q: "Which was NOT one of the Hamburg Temple's new things?", a: "Moving Shabbat to Sunday", w: ["A German sermon", "Choir singing with an organ", "Confirmation for boys and girls"] },
  { t: "beginnings", q: "Who could have confirmation at the Hamburg Temple?", a: "Children of both sexes (boys and girls)", w: ["Only boys", "Only adults", "Only Christians"] },
  { t: "beginnings", q: "Reason #1 they called it a 'temple':", a: "It sounds less foreign and less Jewish than 'synagogue'", w: ["The Torah says to", "It was cheaper", "Napoleon ordered it"] },
  { t: "beginnings", q: "Reason #2 they called it a 'temple':", a: "Hamburg became their Jerusalem. They gave up hope of returning to Zion", w: ["They planned to rebuild the Jerusalem Temple", "It was in an old Roman temple", "Christians named it"] },
  { t: "beginnings", q: "What was the main goal of early Reform, according to Dr. Polster?", a: "Keep Jews Jewish and stop them converting out", w: ["Destroy traditional Judaism", "Get Jews to convert", "Start a Jewish state"] },
  { t: "beginnings", q: "Who founded the Hamburg Temple?", a: "Laymen (not rabbis), 66 Jews", w: ["Abraham Geiger", "The Pope", "Heinrich Heine"] },
  { t: "issues", q: "The big question at the Frankfurt conference was...", a: "Is Hebrew legally (halakhically) necessary for prayer?", w: ["Should Jews convert?", "Should the Sabbath be on Friday?", "Should Jews move to America?"] },
  { t: "issues", q: "'Vernacular' means...", a: "The everyday language people speak", w: ["Ancient Hebrew", "Church Latin", "Secret language"] },
  { t: "issues", q: "Frankel's position on Hebrew in prayer:", a: "Not legally required, but keep it because it's sacred to the people", w: ["Ban Hebrew completely", "Hebrew is required by law", "Pray only in French"] },
  { t: "issues", q: "Frankel later founded which movement?", a: "Conservative Judaism", w: ["Reform Judaism", "Neo-Orthodoxy", "Zionism"] },
  { t: "issues", q: "Frankel's approach is called...", a: "Positive-historical Judaism", w: ["Classical Reform", "Science of Judaism", "Ethical culture"] },
  { t: "issues", q: "What is a 'schism'?", a: "A split or division", w: ["A prayer", "A temple", "A holiday"] },
  { t: "issues", q: "Geiger's position on prayer language:", a: "German (the vernacular) strikes a deeper chord", w: ["Only Hebrew", "Latin like the church", "No prayer at all"] },
  { t: "issues", q: "Why did Geiger NOT want Hebrew to be central?", a: "It would make Judaism a nation, and he saw Judaism as only a religion", w: ["He couldn't read Hebrew", "Hebrew was illegal", "Frankel told him not to"] },
  { t: "issues", q: "Geiger's prayer book took out prayers about...", a: "Returning to Zion, rebuilding the Temple, the ingathering of exiles", w: ["God and peace", "Shabbat and holidays", "Charity"] },
  { t: "issues", q: "Which idea did Geiger's prayer book add?", a: "Hope for the unification of all mankind (universalism)", w: ["Hope for a Jewish king", "Jews are separate from everyone", "Sacrifices in the Temple"] },
  { t: "issues", q: "Geiger REFUSED to...", a: "Move the Sabbath to Sunday (unlike Holdheim)", w: ["Pray in German", "Write a new prayer book", "Go to the Frankfurt conference"] },
  { t: "issues", q: "Which issue did Reform NOT have to tackle to 'be like' Christian neighbours?", a: "Whether to build a Jewish army", w: ["Head covering", "Kashrut", "Saturday vs. Sunday Sabbath"] },
  { t: "issues", q: "Geiger was strongly opposed to...", a: "Hirsch's neo-Orthodoxy and Frankel's conservative views", w: ["Learning German", "All prayer", "Jacobson's temple"] },
  { t: "evolution", q: "The Pittsburgh Platform is also called...", a: "Classical Reform Judaism", w: ["Conservative Judaism", "Neo-Orthodoxy", "Wissenschaft"] },
  { t: "evolution", q: "Pittsburgh said the Jews are...", a: "No longer a nation, but a religious community", w: ["A nation that must return to Palestine", "A race", "Christians"] },
  { t: "evolution", q: "Pittsburgh's view of kashrut (diet) laws:", a: "They fail to impress the modern Jew and are not binding", w: ["They must be kept strictly", "Only on Shabbat", "Only for rabbis"] },
  { t: "evolution", q: "Pittsburgh: which laws are still binding?", a: "Only the moral laws", w: ["All Torah laws", "Only diet laws", "No laws at all"] },
  { t: "evolution", q: "Pittsburgh's view of returning to Palestine:", a: "They expect no return to Palestine", w: ["They must all move there", "Only rabbis should go", "They want to buy it"] },
  { t: "evolution", q: "What happened in 1935 that shook Reform's ideas?", a: "The Nuremberg Laws took German Jews' citizenship away", w: ["The State of Israel was founded", "The Pittsburgh Platform was written", "Jews were emancipated in France"] },
  { t: "evolution", q: "Why did Reform change its views by 1937?", a: "Assimilation failed: even converts weren't accepted as Germans", w: ["Everyone became Orthodox", "Hebrew was banned", "America outlawed Reform"] },
  { t: "evolution", q: "Columbus (1937) on a homeland in Palestine:", a: "All Jewry should help build it as a Jewish homeland", w: ["No return to Palestine ever", "Only for Orthodox Jews", "It never mentions Palestine"] },
  { t: "evolution", q: "Columbus (1937) on Hebrew:", a: "Use Hebrew together with the vernacular", w: ["Ban Hebrew", "Only Hebrew, no English", "Hebrew only for rabbis"] },
  { t: "evolution", q: "The biggest change from Pittsburgh to Columbus:", a: "From 'religion, not a nation' back to 'Jewish people' with a homeland", w: ["From Christian to Jewish", "From English to German", "No change at all"] },
  { t: "evolution", q: "Is Reform Judaism today anti-Israel?", a: "No. That was early Reform; Columbus 1937 already supported a homeland", w: ["Yes, always", "Yes, since 1937", "Reform doesn't exist today"] },
  { t: "evolution", q: "Which group wrote both platforms (adopted 1889, revised 1937)?", a: "The CCAR (Central Conference of American Rabbis)", w: ["The Hamburg Temple", "The Frankfurt Conference", "Napoleon's Sanhedrin"] },
  { t: "evolution", q: "Pittsburgh called Christianity and Islam...", a: "Daughter religions of Judaism", w: ["False religions", "The same as Judaism", "Older than Judaism"] },
  { t: "evolution", q: "Columbus calls itself...", a: "Not a fixed creed but a guide", w: ["Unchangeable law", "A Christian creed", "A peace treaty"] },
  { t: "evolution", q: "Columbus says Torah and revelation are...", a: "A continuous process, adapted in each age", w: ["Fixed forever", "Not important", "Only for Israel"] },
];

// True statements and their false twins
const TF = [
  { t: "conversion", s: "Heine was baptized hoping to get a university or government job.", f: "Heine was baptized because he deeply believed in Christianity." },
  { t: "conversion", s: "Abraham Mendelssohn was the son of Moses Mendelssohn.", f: "Abraham Mendelssohn was the father of Moses Mendelssohn." },
  { t: "conversion", s: "Conversion after emancipation was a choice, not forced.", f: "Conversion after emancipation was forced, like during the Crusades." },
  { t: "conversion", s: "Mendelssohn wrote a letter to his daughter explaining why he raised her Christian.", f: "Mendelssohn wrote a letter to his rabbi explaining why he stayed Jewish." },
  { t: "conversion", s: "Heine later said he never really left Judaism.", f: "Heine later became a Catholic priest." },
  { t: "beginnings", s: "Christians attended the opening of Jacobson's temple.", f: "Only Jews were allowed into Jacobson's temple." },
  { t: "beginnings", s: "The Hamburg Temple added a German sermon and an organ.", f: "The Hamburg Temple banned all music." },
  { t: "beginnings", s: "Calling it a 'temple' showed Reformers gave up hope of returning to Jerusalem.", f: "Calling it a 'temple' showed Reformers planned to rebuild the Temple in Jerusalem." },
  { t: "beginnings", s: "Jacobson said he did not want to undermine the pillars of the faith.", f: "Jacobson said his goal was to undermine traditional Judaism." },
  { t: "beginnings", s: "Early Reform wanted to stop Jews from converting out.", f: "Early Reform wanted Jews to convert to Christianity." },
  { t: "issues", s: "Frankel wanted to keep Hebrew in prayer.", f: "Frankel wanted to remove Hebrew from prayer completely." },
  { t: "issues", s: "Geiger said a German prayer strikes a deeper chord than a Hebrew one.", f: "Frankel said a German prayer strikes a deeper chord than a Hebrew one." },
  { t: "issues", s: "Geiger saw Judaism as a religion, not a nation.", f: "Geiger saw Judaism mainly as a nation that needs its own language." },
  { t: "issues", s: "Geiger's prayer book removed hopes for a Jewish state in Palestine.", f: "Geiger's prayer book added more prayers about returning to Zion." },
  { t: "issues", s: "Frankel is the founder of the Conservative movement.", f: "Geiger is the founder of the Conservative movement." },
  { t: "issues", s: "Geiger refused to move the Sabbath to Sunday.", f: "Geiger moved the Sabbath to Sunday." },
  { t: "evolution", s: "The Pittsburgh Platform said Jews are no longer a nation.", f: "The Pittsburgh Platform said Jews must return to Palestine." },
  { t: "evolution", s: "The Columbus Platform supported building a Jewish homeland in Palestine.", f: "The Columbus Platform rejected any Jewish homeland." },
  { t: "evolution", s: "The Columbus Platform brought back Hebrew alongside the vernacular.", f: "The Columbus Platform banned Hebrew from worship." },
  { t: "evolution", s: "The Nazi Nuremberg Laws (1935) helped push Reform to rethink its views.", f: "Reform changed its views in 1937 because Hebrew became popular in Germany." },
  { t: "evolution", s: "Pittsburgh said only the moral laws are binding.", f: "Pittsburgh said every Torah law, including kashrut, is binding." },
];

// Put events in order (dates are not tested, but the order/evolution is)
const TIMELINE = [
  { y: "1810", e: "Israel Jacobson opens his little \"Temple\" in Seesen", who: "jacobson" },
  { y: "1817-18", e: "Hamburg Temple constitution and dedication", who: "hamburg" },
  { y: "1822-25", e: "Mendelssohn family and Heine convert", who: "heine" },
  { y: "1845", e: "Frankfurt conference: Frankel vs. Geiger on Hebrew", who: "frankel" },
  { y: "1845+", e: "Geiger's new prayer book: national aspect recedes", who: "geiger" },
  { y: "1885", e: "Pittsburgh Platform: Classical Reform", who: "pittsburgh" },
  { y: "1935", e: "Nazi Nuremberg Laws strip German Jews of citizenship", who: null },
  { y: "1937", e: "Columbus Platform: peoplehood, homeland, Hebrew return", who: "columbus" },
];

// Sort statements into two groups
const SORTS = [
  { title: "Heine or Mendelssohn?", a: "heine", b: "mendelssohn", items: [
    ["heine", "Baptism is a ticket of admission"], ["heine", "Wanted a job in Prussia"], ["heine", "Poet who moved to Paris"],
    ["heine", "Could fight for his 'unfortunate brethren' from inside"], ["mendelssohn", "Letter to his daughter"],
    ["mendelssohn", "Christianity is the creed of the most civilized people"], ["mendelssohn", "Jewish form reigned thousands of years ago"],
    ["mendelssohn", "Son of the father of the Haskalah"] ] },
  { title: "Frankel or Geiger?", a: "frankel", b: "geiger", items: [
    ["frankel", "Conserve what is sacred to the people"], ["frankel", "Prevent a schism"], ["frankel", "Positive-historical Judaism"],
    ["frankel", "Founder of Conservative Judaism"], ["geiger", "German prayer strikes a deeper chord"],
    ["geiger", "Don't link Judaism to a nation"], ["geiger", "National aspect must recede"], ["geiger", "Judaism on the crutches of a language"] ] },
  { title: "Pittsburgh (1885) or Columbus (1937)?", a: "pittsburgh", b: "columbus", items: [
    ["pittsburgh", "No longer a nation"], ["pittsburgh", "No return to Palestine"], ["pittsburgh", "Diet and dress laws don't matter"],
    ["pittsburgh", "Only moral laws are binding"], ["columbus", "Help build a Jewish homeland"], ["columbus", "Hebrew with the vernacular"],
    ["columbus", "Judaism is the soul, Israel is the body"], ["columbus", "Keep Sabbath, festivals, inspiring customs"] ] },
  { title: "Jacobson or Hamburg Temple?", a: "jacobson", b: "hamburg", items: [
    ["jacobson", "Purpose: your religious education"], ["jacobson", "Why should we alone remain behind?"],
    ["jacobson", "Wore robes like a Protestant minister"], ["jacobson", "Not a rabbi, opened it in 1810"],
    ["hamburg", "Public worship neglected (nobody knows the language)"], ["hamburg", "German sermon and organ"],
    ["hamburg", "Confirmation for boys and girls"], ["hamburg", "Declared their city their Jerusalem"] ] },
];

// Short answers. pts = key points with keyword patterns for quick marking.
const SHORT = [
  { id: "s1", t: "conversion", q: "Compare Heine's and Mendelssohn's reasons for converting.",
    model: "Heine converted to get ahead in society; he saw the baptismal certificate as a ticket of admission to European culture and a job. Mendelssohn raised his children Christian because he saw Christianity as the religion of the most civilized people today, while Judaism had its day. Both were social or political reasons, not religious ones.",
    pts: [["Heine: ticket / career / get ahead", "ticket|career|job|position|university|doctor|get ahead|discriminat|accept"],
          ["Mendelssohn: creed of most civilized / Judaism had its day", "civiliz|had its day|reigning|now it is the christian|majority|times"],
          ["Both social/political, not religious", "social|political|not religious|secular|not because"]] },
  { id: "s2", t: "conversion", q: "Explain the quote: \"The baptismal certificate is the ticket of admission to European culture.\" Who said it and what does it mean?",
    model: "Heinrich Heine said it. He meant that for a Jew to be fully accepted in European society, get a career and avoid discrimination, he had to be baptized; it was a social move, not a religious belief.",
    pts: [["Names Heine", "heine"], ["Baptism/conversion = way into society", "society|accept|europe|in to|into|admission|career|job|discriminat"], ["Not religious belief", "not religious|social|political|didn.t believe|indifferen"]] },
  { id: "s3", t: "conversion", q: "How was conversion after emancipation different from conversion in the Middle Ages?",
    model: "In the Middle Ages (Crusades, Inquisition) Jews were forced to convert or be killed. After emancipation conversion was a free choice, and with religion playing a smaller role it became a secular, social and political act to be accepted in society.",
    pts: [["Middle Ages: forced", "forc|kill|inquisition|crusade|fear"], ["Now: choice", "choice|chose|choos|free"], ["Secular/social reasons", "secular|social|political|accept|career"]] },
  { id: "s4", t: "beginnings", q: "What was the original intent of the Reform movement according to Jacobson and the Hamburg Temple?",
    model: "Jacobson said his temple was for religious education, not to undermine the pillars of the faith. The Hamburg Temple said public worship was neglected because people no longer knew Hebrew, so they made it attractive and understandable (German sermon, organ, choir) to keep Jews from leaving or converting.",
    pts: [["Religious education / not undermine", "educat|undermine|pillar"], ["Worship neglected / nobody knows Hebrew", "neglect|language|hebrew|understand|meaningful|formula"], ["Keep Jews in, stop conversion / attractive", "keep|convert|attract|bring|access|come back"]] },
  { id: "s5", t: "beginnings", q: "Give two reasons the Reformers called their house of worship a \"temple\".",
    model: "First, \"temple\" sounded less foreign and less Jewish than synagogue, like the places of worship of other religions. Second, by using the name of the destroyed Temple in Jerusalem, they gave up hope of returning to Zion and declared Hamburg their Jerusalem: we are here to stay.",
    pts: [["Less foreign / less Jewish", "foreign|less jewish|other religion|church|buddhist|hindu|fit in|like them"], ["Gave up Jerusalem/Zion, here to stay", "jerusalem|zion|here to stay|restor|israel|return|hamburg"]] },
  { id: "s6", t: "beginnings", q: "List two changes the Hamburg Temple brought into Jewish worship and explain why.",
    model: "It added a German sermon and choir singing with an organ, and confirmation for both boys and girls. The goal was to make worship dignified, understandable and attractive, like their Christian neighbours, because people no longer understood Hebrew and stopped coming.",
    pts: [["Names a real change", "german sermon|sermon|organ|choir|confirm|girls"], ["Second change", "organ|choir|confirm|girls|sermon|german"], ["Why: attract / understand / like neighbours", "attract|understand|neglect|language|like the|christian|dignit|come"]] },
  { id: "s7", t: "issues", q: "Explain the debate between Frankel and Geiger at the Frankfurt conference.",
    model: "They argued whether Hebrew is needed in prayer. Frankel said it is not legally required but must be conserved because it is sacred to the whole people and prevents a schism. Geiger said a German prayer strikes a deeper chord because people understand it, and that Judaism is a religion, not a nation tied to one language.",
    pts: [["Topic: Hebrew vs vernacular in prayer", "hebrew|vernacular|language|german"], ["Frankel: conserve / sacred / unity", "conserv|sacred|schism|unit|keep"], ["Geiger: deeper chord / religion not nation", "deeper chord|understand|nation|religion"]] },
  { id: "s8", t: "issues", q: "Explain Geiger's line: \"the national aspect of Israel must recede into the background.\"",
    model: "In the preface to his new prayer book, Geiger said Judaism is only a religion, not a nation. So prayers about returning to Zion, a Jewish state in Palestine, rebuilding the Temple and the ingathering of exiles were removed, and prayers focused on hope for all mankind instead.",
    pts: [["Religion, not a nation", "religion|not a nation|nation"], ["Removed Zion / state / Temple / Messiah", "zion|palestine|state|temple|messiah|ingather|jerusalem|israel"], ["Prayer book / universal hope", "prayer|mankind|universal|all people|unif"]] },
  { id: "s9", t: "issues", q: "What were the three main issues in Geiger's preface to the Frankfurt prayer book?",
    model: "One: the connection to Israel and Zion is removed from prayer. Two: no more praying for the Messiah, rebuilding the Temple or the ingathering of exiles. Three: universalism, being open to other religions and hoping for the unification of all mankind instead of stressing Jewish separation.",
    pts: [["Israel / Zion", "israel|zion|palestine|state"], ["Messiah / Temple / ingathering", "messiah|temple|ingather|exile"], ["Universalism / other religions", "universal|other religion|mankind|open|separat"]] },
  { id: "s10", t: "evolution", q: "Describe the Pittsburgh Platform (1885). What did Classical Reform believe?",
    model: "It said Jews are no longer a nation but a religious community, so no return to Palestine. Only the moral laws are binding, and laws about diet, priestly purity and dress (like kashrut) don't fit modern life. Judaism is a progressive religion in accord with reason.",
    pts: [["Not a nation / no Palestine", "nation|palestine|zion|return"], ["Only moral laws / drop kashrut, dress", "moral|kashrut|kosher|diet|dress|ritual|ceremon"], ["Modern / progressive / reason", "modern|progress|reason|science"]] },
  { id: "s11", t: "evolution", q: "Why did the Reform movement change its views between 1885 and 1937?",
    model: "By 1937 the Nazis' Nuremberg Laws (1935) showed assimilation had failed: Jews were not accepted as Germans even if they converted, and Hitler went after them whether religion or nation. Zionism in Palestine was succeeding, so Reform brought back Jewish peoplehood and support for a homeland.",
    pts: [["Nazis / Nuremberg Laws / Hitler", "nazi|hitler|nuremberg|germany"], ["Assimilation failed / not accepted", "assimilat|accept|fail|convert"], ["Zionism success / homeland", "zion|homeland|palestine|israel"]] },
  { id: "s12", t: "evolution", q: "Compare the Pittsburgh and Columbus Platforms on Israel and on Hebrew.",
    model: "Pittsburgh (1885) said Jews are not a nation and expect no return to Palestine, and it drops rituals. Columbus (1937) says Judaism is the soul of which Israel is the body, asks all Jews to help build a Jewish homeland, and brings back Hebrew together with the vernacular.",
    pts: [["Pittsburgh: no nation / no Palestine", "pittsburgh|1885|no longer a nation|no return|not a nation"], ["Columbus: homeland / people", "columbus|1937|homeland|build|soul|body|people"], ["Hebrew returns", "hebrew"]] },
  { id: "s13", t: "evolution", q: "Is it right to say Reform Judaism is against Israel? Explain using the evolution of Reform.",
    model: "No. Early Reform (Geiger, Pittsburgh 1885) removed Zion and said Jews are not a nation. But the Columbus Platform (1937) changed this and called on all Jews to help build a Jewish homeland, and Reform today supports Israel.",
    pts: [["No / not today", "no|not true|isn.t|wrong|not anti"], ["Early Reform rejected Zion", "early|pittsburgh|geiger|1885|nation|zion"], ["Columbus supports homeland", "columbus|1937|homeland|build|support"]] },
];
