// All study content. Quotes are from the JH11-21 source book pages on the demo.
// "Polster" lines are from Dr. Polster's classes (Sept 22, 25, 29, Oct 1).

const DEMO_DATE = "2026-10-02T08:30:00-04:00";
const AI_URL = "https://jh-demo-ai.vercel.app/api/chat";
const AI_DAILY_LIMIT = 12;

const SPEAKERS = {
  heine: { name: "Heine", full: "Heinrich Heine", topic: "conversion", img: "img/heine.jpg", page: "p. 13",
    tag: "Converted for a career. Baptism = ticket into European culture." },
  mendelssohn: { name: "Mendelssohn", full: "Abraham Mendelssohn", topic: "conversion", img: "img/mendelssohn.jpg", page: "pp. 11-12",
    tag: "Raised his kids Christian: the creed of the most civilized people." },
  jacobson: { name: "Jacobson", full: "Israel Jacobson", topic: "beginnings", img: "img/jacobson.jpg", page: "p. 14",
    tag: "First Reform 'Temple' (1810). Goal: religious education." },
  hamburg: { name: "Hamburg Temple", full: "Hamburg Temple Constitution", topic: "beginnings", img: "img/temple-illustration.jpg", page: "p. 15",
    tag: "Worship neglected, so: German sermon, organ, choir, confirmation." },
  frankel: { name: "Frankel", full: "Zecharias Frankel", topic: "issues", img: "img/frankel.jpg", page: "pp. 17-18",
    tag: "Team Hebrew. Conserve what is sacred. Founder of Conservative." },
  geiger: { name: "Geiger", full: "Abraham Geiger", topic: "issues", img: "img/geiger.jpg", page: "pp. 18, 22-23",
    tag: "Team German. Judaism is a religion, not a nation." },
  pittsburgh: { name: "Pittsburgh Platform", full: "Pittsburgh Platform (1885)", topic: "evolution", img: "img/wise.jpg", page: "pp. 24-25",
    tag: "Classical Reform: no longer a nation, no return to Palestine." },
  columbus: { name: "Columbus Platform", full: "Columbus Platform (1937)", topic: "evolution", img: null, badge: "1937", page: "pp. 26-28",
    tag: "After Nazi laws: Jewish people again, support a homeland, Hebrew back." },
};

const TOPICS = {
  conversion: "Conversion",
  beginnings: "Reform: Beginnings",
  issues: "Reform: Main Issues",
  evolution: "Reform: Evolution",
};

// star = Dr. Polster flagged it in class
const QUOTES = [
  // Heine
  { id: "h1", who: "heine", star: true, text: "The baptismal certificate is the ticket of admission to European culture.",
    clue: "Baptism = a ticket in. Conversion as a social move." },
  { id: "h2", who: "heine", text: "From the nature of my thinking you can deduce that baptism is a matter of indifference to me.",
    clue: "Baptism means nothing religious to him." },
  { id: "h3", who: "heine", text: "For me perhaps its significance will be that I can better devote myself to championing the rights of my unfortunate brethren.",
    clue: "Converting so he can fight for Jews from the inside." },
  { id: "h4", who: "heine", text: "I hold it beneath my dignity and a stain on my honor to undergo conversion in order to obtain a position in Prussia.",
    clue: "Ashamed to convert just for a job in Prussia." },
  { id: "h5", who: "heine", text: "I'll turn Catholic yet for spite, and hang myself.",
    clue: "Bitter joke about converting." },
  { id: "h6", who: "heine", text: "I make no secret of my Judaism, to which I have not returned, because I never left it.",
    clue: "Later in life he kept his Jewishness." },
  { id: "h7", who: "heine", text: "Where they burn books, they ultimately burn people.",
    clue: "From his play. Dr. Polster said to note it (comes back with the Nazis)." },
  // Mendelssohn
  { id: "m1", who: "mendelssohn", star: true, text: "We have educated you and your brothers and sister in the Christian faith, because it is the creed of most civilized people.",
    clue: "Letter to his daughter. Christianity = religion of the civilized." },
  { id: "m2", who: "mendelssohn", star: true, text: "Some thousands of years ago the Jewish form was the reigning one, then the heathen form, and now it is the Christian.",
    clue: "Judaism 'had its day'. Now it's Christianity's time." },
  { id: "m3", who: "mendelssohn", text: "The outward form of religion your teacher has given you is historical, and changeable like all human ordinances.",
    clue: "Religion's outer form changes over time." },
  { id: "m4", who: "mendelssohn", text: "I know it, I believe it, I live in this faith, and this is my religion.",
    clue: "His religion = conscience and being good, not Judaism." },
  { id: "m5", who: "mendelssohn", text: "By pronouncing your confession of faith you have fulfilled the claims of society on you, and obtained the name of a Christian.",
    clue: "Speaking to his daughter Fanny at her confirmation." },
  { id: "m6", who: "mendelssohn", text: "Because it is the religious form acceptable to the majority of civilized human beings.",
    clue: "Why he and his wife became Christian." },
  // Jacobson
  { id: "j1", who: "jacobson", star: true, text: "What I had in mind when I first thought about building this temple was your religious education.",
    clue: "Opening line of his dedication speech (first 4 lines of p. 14)." },
  { id: "j2", who: "jacobson", star: true, text: "Be it far from me that I should have any secret intention to undermine the pillars of your faith.",
    clue: "Not trying to destroy Judaism." },
  { id: "j3", who: "jacobson", star: true, text: "On all sides, enlightenment opens up new areas for development. Why should we alone remain behind?",
    clue: "Everyone is progressing, so should we." },
  { id: "j4", who: "jacobson", text: "Who would dare to deny that our service is sickly because of many useless things, that in part it has degenerated into a thoughtless recitation of prayers and formulas.",
    clue: "Old services felt like empty formulas." },
  { id: "j5", who: "jacobson", text: "If I do seek here first some rapprochement between you and our Christian neighbors, I would ask more for your gratitude and honest help than for your criticism.",
    clue: "Bringing Jews and Christians closer." },
  // Hamburg
  { id: "t1", who: "hamburg", star: true, text: "Since public worship has for some time been neglected by so many, because of the ever decreasing knowledge of the language in which alone it has until now been conducted...",
    clue: "First lines of the constitution: nobody understands Hebrew anymore." },
  { id: "t2", who: "hamburg", text: "Specifically, there shall be introduced at such services a German sermon, and choral singing to the accompaniment of an organ.",
    clue: "New things added to worship." },
  { id: "t3", who: "hamburg", text: "The children of both sexes, after having received adequate schooling in the teachings of the faith, shall be accepted as confirmants of the Mosaic religion.",
    clue: "Confirmation for boys AND girls." },
  { id: "t4", who: "hamburg", text: "Convinced of the necessity to restore public worship to its deserving dignity and importance.",
    clue: "Make worship dignified again." },
  { id: "t5", who: "hamburg", text: "By adopting the designation traditionally reserved for the fallen Temple of Jerusalem, the Reformers symbolically relinquished the hope of Israel's restoration and declared Hamburg their Jerusalem.",
    clue: "Footnote: why they called it a 'Temple'." },
  // Frankel
  { id: "f1", who: "frankel", star: true, text: "Now it is necessary to conserve the things which are truly sacred to the entire people, to prevent any schism in Israel.",
    clue: "CONSERVE = Conservative movement. Keep Hebrew so Jews don't split." },
  { id: "f2", who: "frankel", text: "In order to understand Judaism in the present one must look back and investigate its past.",
    clue: "Positive-historical Judaism." },
  { id: "f3", who: "frankel", star: true, text: "The positive forms of Judaism are deeply rooted within its innermost being and must not be discarded coldly and heartlessly.",
    clue: "Don't throw tradition away. Top left of p. 18. Dr. Polster (Oct 1): 'That's a quote that could be on tomorrow.'" },
  { id: "f4", who: "frankel", text: "The Zeitgeist is as fickle as the times. Besides, it is cold.",
    clue: "Don't just follow the spirit of the times." },
  { id: "f5", who: "frankel", text: "Rather than creating new parties, we must make peace between the existing ones.",
    clue: "Unity. Don't split the people." },
  { id: "f6", who: "frankel", text: "It is the pride of Judaism that no person, and no social class, may presume authority, but that every decision must evolve organically from principles.",
    clue: "Decisions need principles." },
  // Geiger
  { id: "g1", who: "geiger", star: true, text: "A German prayer strikes a deeper chord than a Hebrew prayer.",
    clue: "You understand German, so it means more." },
  { id: "g2", who: "geiger", star: true, text: "No member of this conference would wish to link Judaism to a particular nation.",
    clue: "Judaism = religion, not a nation (p. 18, right column)." },
  { id: "g3", who: "geiger", star: true, text: "Consequently, the national aspect of Israel must recede into the background.",
    clue: "Preface to his prayer book. Dr. Polster: commit it to memory!" },
  { id: "g4", who: "geiger", text: "Anyone who imagines Judaism to be walking on the crutches of a language deeply offends it.",
    clue: "Judaism doesn't need Hebrew to stand." },
  { id: "g5", who: "geiger", text: "The Hebrew language has ceased to be alive for the people.",
    clue: "Nobody really speaks Hebrew anymore." },
  { id: "g6", who: "geiger", text: "Wholly faded from our consciousness is the belief in the restoration of a Jewish State in Palestine.",
    clue: "Prayer book preface: no more praying for Zion." },
  { id: "g7", who: "geiger", text: "The look into the future should arouse the happy hope in the unification of all mankind, in truth, in justice, and in peace.",
    clue: "Universalism." },
  { id: "g8", who: "geiger", text: "The separation between Israel and the other peoples, which existed at one time, has no right to be expressed in prayer.",
    clue: "Don't pray about being separate." },
  // Pittsburgh
  { id: "p1", who: "pittsburgh", star: true, text: "We consider ourselves no longer a nation, but a religious community, and therefore expect neither a return to Palestine, nor a sacrificial worship under the sons of Aaron.",
    clue: "Fifth principle. Classical Reform." },
  { id: "p2", who: "pittsburgh", text: "All such Mosaic and rabbinical laws as regulate diet, priestly purity, and dress ... fail to impress the modern Jew with a spirit of priestly holiness.",
    clue: "Fourth principle: drop kashrut and dress rules." },
  { id: "p3", who: "pittsburgh", star: true, text: "Today we accept as binding only the moral laws, and maintain only such ceremonies as elevate and sanctify our lives.",
    clue: "Third principle, bottom of p. 24. Keep moral laws (don't kill), drop ritual laws (kosher, Shabbat). Classical Reform." },
  { id: "p4", who: "pittsburgh", text: "We recognize in Judaism a progressive religion, ever striving to be in accord with the postulates of reason.",
    clue: "Sixth principle: religion + reason." },
  { id: "p5", who: "pittsburgh", text: "We recognize in every religion an attempt to grasp the Infinite.",
    clue: "First principle: all religions have truth." },
  { id: "p6", who: "pittsburgh", text: "We reject as ideas not rooted in Judaism the beliefs both in bodily resurrection and in Gehenna and Eden.",
    clue: "Seventh principle: no hell and paradise." },
  // Columbus
  { id: "c8", who: "columbus", star: true, text: "In view of the changes that have taken place in the modern world and the consequent need of stating anew the teachings of Reform Judaism...",
    clue: "Opening line, middle of p. 26. Dr. Polster (Oct 1): a response to the coming disaster (Nazis, Holocaust). We have to rethink who we are." },
  { id: "c1", who: "columbus", star: true, text: "Judaism is the soul of which Israel is the body.",
    clue: "Jewish people (Israel) matter again." },
  { id: "c2", who: "columbus", star: true, text: "We affirm the obligation of all Jewry to aid in its upbuilding as a Jewish homeland.",
    clue: "Support a homeland in Palestine. Opposite of 1885." },
  { id: "c3", who: "columbus", text: "The use of Hebrew, together with the vernacular, in our worship and instruction.",
    clue: "Hebrew comes back." },
  { id: "c4", who: "columbus", text: "The preservation of the Sabbath, festivals and Holy Days, the retention and development of such customs, symbols and ceremonies as possess inspirational value.",
    clue: "Bring back meaningful customs." },
  { id: "c5", who: "columbus", text: "Judaism is the historical religious experience of the Jewish people.",
    clue: "Peoplehood is back." },
  { id: "c6", who: "columbus", text: "It presents them not as a fixed creed but as a guide for the progressive elements of Jewry.",
    clue: "Guide, not fixed rules." },
  { id: "c7", who: "columbus", text: "Not only a haven of refuge for the oppressed but also a center of Jewish culture and spiritual life.",
    clue: "What Palestine should be (1937, Nazi era)." },
];

// Dr. Polster's own lines from class
const POLSTER = [
  { text: "It's not memorizing the quote. It's understanding who's associated with that particular quote.", about: "How the demo works" },
  { text: "Highlight that, underline it, circle it, commit it to memory. It's on the demo on Friday. Period.", about: "Geiger: \"the national aspect of Israel must recede into the background\"" },
  { text: "Don't look at the other stuff. It's just on that stuff.", about: "Demo scope" },
  { text: "Dates don't matter to me.", about: "No dates on the demo (unless he says so)" },
  { text: "It wasn't a religious move. It was a political move. Or a social move.", about: "Heine and Mendelssohn converting" },
  { text: "There's a big difference between conversion of choice and conversion out of fear.", about: "Then vs. the Inquisition and Crusades" },
  { text: "That's the OG of the Reform movement.", about: "Jacobson and the Hamburg Temple's intent" },
  { text: "We're here to stay. We're in Germany. This is our Beit HaMikdash.", about: "Why they called it a \"temple\"" },
  { text: "We have to conserve. We have to conserve.", about: "Frankel, founder of the Conservative movement" },
  { text: "Jews are a religion, Geiger says. We're not a people. We're not a nation.", about: "Geiger at Frankfurt" },
  { text: "Everybody should be like Mike.", about: "Reform wanting to look like their Christian neighbours" },
  { text: "Nobody leaves this room thinking that Reform Jews stand for anti-Israel. It's not true.", about: "Early Reform vs. Reform today" },
  { text: "You're going to look at the 3 questions and you're going to say, 'I don't like this one.' You're going to cross it out.", about: "Short answers: pick 2 of 3" },
  { text: "I do the most recent stuff on the demo. So the stuff that we're doing today will be on the demo.", about: "Oct 1: Pittsburgh and Columbus ARE on the demo" },
  { text: "If you focus on quotes, you'll be good.", about: "Short answers: mostly 'who said this, what does it mean, why does it matter'. Maybe one compare question." },
  { text: "We accept as binding only the moral laws. Good quote.", about: "Pittsburgh Platform, 3rd principle. Moral law = don't kill. Drop kosher, Shabbat, bris." },
  { text: "The pendulum is going to swing back and the reform movement is going to re-reform.", about: "Frankel (Hebrew) → Geiger (German) → Pittsburgh (most liberal) → Columbus swings back toward tradition" },
  { text: "This is not reform Judaism today.", about: "Pittsburgh = Classical Reform, not Reform today" },
  { text: "You will be underwhelmed.", about: "The demo is easy if you know the quotes" },
  { text: "Hopefully you'll have the ability on a sit-down within 2 seconds to be able to identify that quote.", about: "Quote speed" },
];

// Multiple-choice facts, checked against the JH11-21 source book.
// a = correct answer, w = wrong answers. Wrong answers are real ideas from OTHER people/sources, so you have to know who is who.
const FACTS = [
  { t: "conversion", q: "Why was conversion after emancipation different from conversion in the Middle Ages?", a: "It was a free choice, more a social or secular act than a religious one", w: ["It was forced by the threat of death, like the Inquisition", "It happened because Jews came to believe in Jesus", "It was ordered by Napoleon's Sanhedrin"] },
  { t: "conversion", q: "Heine was baptized in 1825 mainly because he hoped to...", a: "Get a doctorate and a career as a civil servant or professor", w: ["Raise his children in the creed of the most civilized people", "Bring Jews and Christians closer in a common service", "Show that Judaism's outward form had had its day"] },
  { t: "conversion", q: "What actually happened after Heine converted?", a: "He never got the position he wanted and later left Germany for Paris", w: ["He got the chair at the University of Munich", "He became a Lutheran minister in Prussia", "He returned to Judaism and became a Reform leader"] },
  { t: "conversion", q: "Heine says baptism, for him personally, is...", a: "A matter of indifference, not important even symbolically", w: ["The creed of most civilized people", "The way to find salvation and peace of mind", "Historical and changeable like all human ordinances"] },
  { t: "conversion", q: "What good does Heine hope might come from his baptism?", a: "He can better fight for the rights of his \"unfortunate brethren\"", w: ["His children will be accepted as Germans", "He can bring Christians into the synagogue", "He can rebuild the Temple in Jerusalem"] },
  { t: "conversion", q: "Abraham Mendelssohn wrote his letter to his daughter Fanny when she...", a: "Was confirmed into the Christian (Lutheran) church", w: ["Got married to a Christian", "Decided to return to Judaism", "Started studying at a Jewish school"] },
  { t: "conversion", q: "What does Mendelssohn say is his real religion?", a: "Conscience and an inclination to all that is good, true and right", w: ["Lutheran Christianity, which he chose for his whole family", "The moral laws of the Torah, without the rituals", "The Jewish faith his father Moses taught him"] },
  { t: "conversion", q: "Mendelssohn's argument for raising his kids Christian is that...", a: "Judaism had its day; Christianity is now the creed of most civilized people", w: ["Jews are discriminated against, so baptism is a ticket into society", "He was ashamed to convert just to get a job", "Christianity is the only true religion"] },
  { t: "conversion", q: "Dr. Polster: what's the difference between Heine's and Mendelssohn's reasons?", a: "Heine: convert to get ahead. Mendelssohn: Christianity is the religion of today", w: ["Heine truly believed in Jesus. Mendelssohn only did it for a job", "Heine was forced to convert. Mendelssohn chose it freely", "Heine wanted to go to Paris. Mendelssohn wanted to go to Palestine"] },
  { t: "conversion", q: "What do Heine's and Mendelssohn's conversions have in common?", a: "Both were social or political moves, not religious belief", w: ["Both were forced, like in the Crusades", "Both wanted a Jewish homeland", "Both later led Reform temples"] },
  { t: "conversion", q: "In Heine's quote, \"European culture\" is what baptism gives you...", a: "A ticket of admission to", w: ["Salvation from", "A stain on your honor in", "A crutch to walk in"] },
  { t: "beginnings", q: "What was the main aim of early Reform, according to the source book?", a: "Change Jewish practice so Jews would stop assimilating and converting", w: ["Get Jews to join Protestant churches", "Prepare Jews to return to Palestine", "Study Judaism with scientific methods (Wissenschaft)"] },
  { t: "beginnings", q: "Who was Israel Jacobson?", a: "A layman, not a rabbi, who opened a little \"Temple\" in Seesen", w: ["The rabbi who wrote the Frankfurt prayer book", "The chair of the Pittsburgh conference", "A Christian minister who helped Jews"] },
  { t: "beginnings", q: "Which was part of the opening of Jacobson's Temple?", a: "Christians attended, and hymns were sung with an organ in German and Hebrew", w: ["Prayers were only in Hebrew, with no music", "Only rabbis were allowed inside", "It was declared the new Jerusalem in its constitution"] },
  { t: "beginnings", q: "Jacobson says what he first had in mind when building his temple was...", a: "Your religious education", w: ["Restoring public worship to its deserving dignity", "Preventing any schism in Israel", "Making Judaism a progressive religion"] },
  { t: "beginnings", q: "Jacobson complains the traditional service had become...", a: "A thoughtless recitation of prayers and formulas", w: ["Too German and too modern", "A sacrificial worship under the sons of Aaron", "Linked to a particular nation"] },
  { t: "beginnings", q: "Jacobson wanted \"rapprochement\" (getting closer) between Jews and...", a: "Their Christian neighbours", w: ["Orthodox rabbis", "The Jews of Palestine", "The Prussian army"] },
  { t: "beginnings", q: "Why, says the Hamburg Temple constitution, was public worship neglected?", a: "Fewer and fewer people knew the language it was held in (Hebrew)", w: ["The services were too short", "The government banned Jewish worship", "People wanted to return to Zion"] },
  { t: "beginnings", q: "Which change did the Hamburg Temple NOT introduce?", a: "Moving the Sabbath to Sunday", w: ["A German sermon", "Choral singing with an organ", "Confirmation for both boys and girls"] },
  { t: "beginnings", q: "Who founded the Hamburg Temple?", a: "66 Jews led by laymen, not rabbis", w: ["Abraham Geiger and the Frankfurt rabbis", "Israel Jacobson alone", "The Central Conference of American Rabbis"] },
  { t: "beginnings", q: "By calling it a \"temple\", the Reformers symbolically...", a: "Gave up the hope of returning to Jerusalem: Hamburg became their Jerusalem", w: ["Promised to rebuild the Temple in Jerusalem", "Became a branch of the Lutheran church", "Brought back animal sacrifices"] },
  { t: "beginnings", q: "Besides \"here to stay\", the other reason for the name \"temple\" was...", a: "It sounded less foreign and set it apart from the traditional synagogue", w: ["The Talmud requires it", "Napoleon ordered all synagogues renamed", "It was the name of Jacobson's school"] },
  { t: "issues", q: "The question at the Frankfurt conference (1845) was...", a: "Is praying in Hebrew legally necessary, and if not, should it be kept?", w: ["Should Jews move the Sabbath to Sunday?", "Are Jews a nation that should return to Palestine?", "Should Jews convert to get government jobs?"] },
  { t: "issues", q: "What did the Frankfurt committee report say about Hebrew?", a: "Not objectively necessary, but keep it for key prayers like the Shema", w: ["Hebrew must be removed completely", "Every prayer must stay in Hebrew by law", "Hebrew is only for rabbis"] },
  { t: "issues", q: "Frankel's main reason for keeping Hebrew:", a: "It is sacred to the whole people, and dropping it would split Israel (a schism)", w: ["A German prayer strikes a deeper chord, so Hebrew is needed less", "Hebrew is the language of a separate nation, and Jews are a nation", "Halakha clearly says every prayer must be said in Hebrew"] },
  { t: "issues", q: "Frankel calls his approach...", a: "Positive-historical Judaism", w: ["Classical Reform", "Neo-Orthodoxy", "The Science of Judaism"] },
  { t: "issues", q: "What does Frankel say about the Zeitgeist (spirit of the times)?", a: "It is as fickle as the times, and cold", w: ["It strikes a deeper chord", "It is our ally in our mission", "It opens up new areas for development"] },
  { t: "issues", q: "What did Frankel do when the conference voted to cut down Hebrew?", a: "He left the conference and went on to start another movement", w: ["He agreed and wrote a German prayer book", "He moved the Sabbath to Sunday", "He converted to Christianity"] },
  { t: "issues", q: "Frankel is seen as the founder of...", a: "Conservative Judaism", w: ["Reform Judaism", "Neo-Orthodoxy", "Zionism"] },
  { t: "issues", q: "Geiger admits Hebrew was his first mother tongue, yet he says...", a: "A German prayer strikes a deeper chord than a Hebrew prayer", w: ["Hebrew must prevail in every service", "German prayer is a blatant untruth", "Hebrew is the creed of most civilized people"] },
  { t: "issues", q: "Why does Geiger say making Hebrew central is dangerous?", a: "A separate language marks a separate nation, and Judaism is a religion, not a nation", w: ["Hebrew is too hard for the rabbis themselves to read properly", "Christians would stop coming to the services and the reception", "The Talmud forbids praying in Hebrew outside of Jerusalem"] },
  { t: "issues", q: "\"Walking on the crutches of a language\": Geiger means...", a: "Judaism doesn't depend on Hebrew to survive", w: ["Judaism needs Hebrew to stand", "Jews should learn more languages", "German is a weak language for prayer"] },
  { t: "issues", q: "Geiger's prayer book preface: \"the national aspect of Israel must...\"", a: "Recede into the background", w: ["Be restored in Palestine", "Be conserved for the whole people", "Be the body of which Judaism is the soul"] },
  { t: "issues", q: "Which hope did Geiger's prayer book take OUT?", a: "A Jewish state in Palestine, a rebuilt Temple, and the ingathering of exiles", w: ["Hope for peace and justice", "Hope for the unification of all mankind", "Joy that barriers between peoples are falling"] },
  { t: "issues", q: "Geiger says praying for a return to Zion would be...", a: "A blatant untruth", w: ["A matter of indifference", "A stain on his honor", "Sacred to the entire people"] },
  { t: "issues", q: "Geiger was a reformer, but he still REFUSED to...", a: "Move the Sabbath to Sunday or abolish circumcision", w: ["Pray in German", "Write a new prayer book", "Remove prayers about Zion"] },
  { t: "issues", q: "Which issue did Reform face in trying to be like its Christian neighbours?", a: "Head covering, kashrut, Sabbath day, and prayer language", w: ["Whether to build a Jewish army", "Whether to elect a Jewish king", "Whether to move to America"] },
  { t: "evolution", q: "The \"Treifa Banquet\" (1883) for new Reform rabbis served clams and shrimp. Why does it matter?", a: "Being \"like them\" meant losing what makes Jews Jewish, like kashrut", w: ["It showed Reform wanted to return to Palestine", "It was the start of Conservative Judaism", "It was a protest against the Nuremberg Laws"] },
  { t: "evolution", q: "Dr. Polster's \"pendulum\": which order goes from most traditional to most liberal?", a: "Frankel → Geiger → Pittsburgh, then Columbus swings back", w: ["Pittsburgh → Geiger → Frankel → Columbus", "Columbus → Pittsburgh → Frankel → Geiger", "Geiger → Frankel → Columbus → Pittsburgh"] },
  { t: "evolution", q: "\"In view of the changes that have taken place in the modern world...\" opens which document, and why?", a: "The Columbus Platform, responding to the Nazi threat: Reform had to rethink who it is", w: ["The Pittsburgh Platform, celebrating modern science", "Geiger's prayer book, removing Zion", "The Hamburg Temple constitution, adding an organ"] },
  { t: "evolution", q: "In Pittsburgh's \"only the moral laws\", what is an example of a moral law?", a: "Don't kill", w: ["Keep kosher", "Keep Shabbat", "Do a bris (circumcision)"] },
  { t: "evolution", q: "The Pittsburgh Platform (1885) is known as...", a: "Classical Reform Judaism", w: ["Positive-historical Judaism", "The Guiding Principles of Reform Judaism", "Neo-Orthodoxy"] },
  { t: "evolution", q: "Pittsburgh's 5th principle says Jews are...", a: "No longer a nation, but a religious community", w: ["The body of which Judaism is the soul", "A people who must build a homeland", "A nation tied to the Hebrew language"] },
  { t: "evolution", q: "Pittsburgh: which laws are still binding?", a: "Only the moral laws", w: ["All Mosaic and rabbinic laws", "The diet, purity and dress laws", "Only the laws about the Sabbath"] },
  { t: "evolution", q: "Pittsburgh says laws about diet, priestly purity and dress...", a: "Fail to impress the modern Jew and get in the way of spiritual elevation", w: ["Possess inspirational value and must be kept", "Must be decided by the whole people", "Should be kept in Hebrew"] },
  { t: "evolution", q: "How does Pittsburgh see other religions?", a: "Every religion is an attempt to grasp the Infinite; Christianity and Islam are daughter religions", w: ["They are all false, and only Judaism grasps the Infinite", "Judaism should merge with Christianity into one religion", "Christianity and Islam are older religions that Judaism came from"] },
  { t: "evolution", q: "Pittsburgh rejects belief in...", a: "Bodily resurrection and Gehenna and Eden (hell and paradise)", w: ["The immortal soul and the divine nature of the human spirit", "One God who rules the world through law and love", "Working for justice between rich and poor"] },
  { t: "evolution", q: "What pushed Reform to change its views by 1937?", a: "The Nuremberg Laws showed assimilation failed, and Zionism in Palestine was working", w: ["The State of Israel had just been founded and needed support", "Geiger's prayer book was banned by the government in Germany", "Most Reform Jews in America had become Orthodox again"] },
  { t: "evolution", q: "By 1937, German Jews found they were not accepted as Germans...", a: "Even if they had converted to Christianity", w: ["Unless they spoke Hebrew", "Unless they moved to Hamburg", "Only if they kept kosher"] },
  { t: "evolution", q: "Columbus (1937) says about Palestine:", a: "All Jewry must help build it as a Jewish homeland", w: ["Jews expect no return to Palestine", "The hope for it has wholly faded", "Only Orthodox Jews should go"] },
  { t: "evolution", q: "\"Judaism is the soul of which Israel is the body\" means...", a: "The Jewish people (peoplehood) matters again, not just the religion", w: ["Jews are only a religious community", "The body doesn't matter, only the soul", "Israel should be a Christian state"] },
  { t: "evolution", q: "Columbus on Hebrew:", a: "Use Hebrew together with the vernacular in worship and teaching", w: ["Hebrew has ceased to be alive for the people", "A German prayer strikes a deeper chord", "Hebrew only, no vernacular"] },
  { t: "evolution", q: "Columbus on rituals and customs:", a: "Keep the Sabbath, festivals and customs that have inspirational value", w: ["Only the moral laws are binding", "Diet and dress laws obstruct spiritual elevation", "Get rid of all ceremonies"] },
  { t: "evolution", q: "Columbus presents its principles as...", a: "Not a fixed creed but a guide", w: ["Unchangeable law from Sinai", "The constitution of a Jewish state", "A list of things to stop doing"] },
  { t: "evolution", q: "Biggest change from Pittsburgh to Columbus:", a: "From \"religion, not a nation\" to \"Jewish people\" with support for a homeland", w: ["From Hebrew prayer to German prayer, and dropping Israel", "From supporting a homeland in Zion to rejecting one", "From dropping kashrut to making it binding for all Jews"] },
  { t: "evolution", q: "Is it fair to call Reform Judaism today anti-Israel?", a: "No. That was early Reform; by 1937 Reform supported a Jewish homeland", w: ["Yes, Reform has always rejected Israel", "Yes, Columbus rejected any homeland", "Only the Hamburg Temple supports Israel"] },
];

// True statements and their false twins. The false one is close to the truth, so read carefully.
const TF = [
  { t: "conversion", s: "Heine converted hoping to get a university or government job.", f: "Mendelssohn converted hoping to get a university or government job." },
  { t: "conversion", s: "Heine's conversion did not get him the job he wanted.", f: "Heine's conversion got him a chair at the University of Munich." },
  { t: "conversion", s: "Mendelssohn wrote to his daughter that Christianity is the creed of most civilized people.", f: "Heine wrote to his daughter that Christianity is the creed of most civilized people." },
  { t: "conversion", s: "Heine called the baptismal certificate a ticket of admission to European culture.", f: "Mendelssohn called the baptismal certificate a ticket of admission to European culture." },
  { t: "conversion", s: "Abraham Mendelssohn was the son of Moses Mendelssohn.", f: "Abraham Mendelssohn was the father of Moses Mendelssohn." },
  { t: "conversion", s: "After emancipation, conversion was usually a choice made for social reasons.", f: "After emancipation, conversion was usually forced, like in the Inquisition." },
  { t: "conversion", s: "Heine later said he never really left Judaism.", f: "Heine later said Judaism had had its day and Christianity was the religion of today." },
  { t: "beginnings", s: "Israel Jacobson was not a rabbi.", f: "Israel Jacobson was the chief rabbi of Hamburg." },
  { t: "beginnings", s: "Christians attended the opening of Jacobson's temple.", f: "Only Jews were allowed at the opening of Jacobson's temple." },
  { t: "beginnings", s: "Jacobson said he had no secret plan to undermine the pillars of the faith.", f: "The Hamburg Temple said it had no secret plan to undermine the pillars of the faith." },
  { t: "beginnings", s: "The Hamburg Temple brought in confirmation for both boys and girls.", f: "The Hamburg Temple brought in confirmation for boys only." },
  { t: "beginnings", s: "The Hamburg Temple said worship was neglected because people knew less and less Hebrew.", f: "The Hamburg Temple said worship was neglected because the services were in German." },
  { t: "beginnings", s: "Calling it a \"temple\" showed the Reformers gave up hope of returning to Jerusalem.", f: "Calling it a \"temple\" showed the Reformers planned to rebuild the Temple in Jerusalem." },
  { t: "beginnings", s: "Early Reform tried to stop Jews from converting out.", f: "Early Reform tried to get Jews ready to convert." },
  { t: "issues", s: "Frankel wanted to keep Hebrew in prayer.", f: "Frankel wanted a purely German service." },
  { t: "issues", s: "Geiger said a German prayer strikes a deeper chord than a Hebrew one.", f: "Frankel said a German prayer strikes a deeper chord than a Hebrew one." },
  { t: "issues", s: "Frankel wanted to conserve what is sacred to the whole people to prevent a schism.", f: "Geiger wanted to conserve what is sacred to the whole people to prevent a schism." },
  { t: "issues", s: "Geiger said no one at the conference would want to link Judaism to a particular nation.", f: "Frankel said no one at the conference would want to link Judaism to a particular nation." },
  { t: "issues", s: "Geiger's prayer book removed the hope for a Jewish state in Palestine.", f: "Geiger's prayer book added more prayers for a Jewish state in Palestine." },
  { t: "issues", s: "Frankel is seen as the founder of Conservative Judaism.", f: "Geiger is seen as the founder of Conservative Judaism." },
  { t: "issues", s: "Geiger refused to move the Sabbath to Sunday.", f: "Geiger moved the Sabbath to Sunday." },
  { t: "evolution", s: "The Pittsburgh Platform said Jews are no longer a nation.", f: "The Columbus Platform said Jews are no longer a nation." },
  { t: "evolution", s: "The Columbus Platform asked all Jews to help build a Jewish homeland.", f: "The Pittsburgh Platform asked all Jews to help build a Jewish homeland." },
  { t: "evolution", s: "The Columbus Platform brought back Hebrew together with the vernacular.", f: "The Pittsburgh Platform brought back Hebrew together with the vernacular." },
  { t: "evolution", s: "\"In view of the changes that have taken place in the modern world\" is how the Columbus Platform begins.", f: "\"In view of the changes that have taken place in the modern world\" is how the Pittsburgh Platform begins." },
  { t: "evolution", s: "Dr. Polster said Pittsburgh (Classical Reform) is not what Reform Judaism stands for today.", f: "Dr. Polster said Pittsburgh is exactly what Reform Judaism stands for today." },
  { t: "evolution", s: "Pittsburgh said only the moral laws are binding.", f: "Columbus said only the moral laws are binding." },
  { t: "evolution", s: "The Nuremberg Laws (1935) helped show Reform that assimilation had failed.", f: "The founding of the State of Israel pushed Reform to write the Columbus Platform." },
  { t: "evolution", s: "Columbus said \"Judaism is the soul of which Israel is the body.\"", f: "Pittsburgh said \"Judaism is the soul of which Israel is the body.\"" },
];

// Put events in order (dates are not tested, but the order/evolution is)
const TIMELINE = [
  { y: "1810", e: "Israel Jacobson opens his little \"Temple\" in Seesen", who: "jacobson" },
  { y: "1817-18", e: "Hamburg Temple constitution and dedication", who: "hamburg" },
  { y: "1822-25", e: "Mendelssohn family and Heine convert", who: "heine" },
  { y: "1845", e: "Frankfurt conference: Frankel vs. Geiger on Hebrew", who: "frankel" },
  { y: "1845+", e: "Geiger's new prayer book: national aspect recedes", who: "geiger" },
  { y: "1885", e: "Pittsburgh Platform: Classical Reform", who: "pittsburgh" },
  { y: "1935", e: "Nazi Nuremberg Laws strip German Jews of citizenship", who: null },
  { y: "1937", e: "Columbus Platform: peoplehood, homeland, Hebrew return", who: "columbus" },
];

// Sort statements into two groups
const SORTS = [
  { title: "Heine or Mendelssohn?", a: "heine", b: "mendelssohn", items: [
    ["heine", "Baptism is a ticket of admission"], ["heine", "Wanted a job in Prussia"], ["heine", "Poet who moved to Paris"],
    ["heine", "Could fight for his 'unfortunate brethren' from inside"], ["mendelssohn", "Letter to his daughter"],
    ["mendelssohn", "Christianity is the creed of the most civilized people"], ["mendelssohn", "Jewish form reigned thousands of years ago"],
    ["mendelssohn", "Son of the father of the Haskalah"] ] },
  { title: "Frankel or Geiger?", a: "frankel", b: "geiger", items: [
    ["frankel", "Conserve what is sacred to the people"], ["frankel", "Prevent a schism"], ["frankel", "Positive-historical Judaism"],
    ["frankel", "Founder of Conservative Judaism"], ["geiger", "German prayer strikes a deeper chord"],
    ["geiger", "Don't link Judaism to a nation"], ["geiger", "National aspect must recede"], ["geiger", "Judaism on the crutches of a language"] ] },
  { title: "Pittsburgh (1885) or Columbus (1937)?", a: "pittsburgh", b: "columbus", items: [
    ["pittsburgh", "No longer a nation"], ["pittsburgh", "No return to Palestine"], ["pittsburgh", "Diet and dress laws don't matter"],
    ["pittsburgh", "Only moral laws are binding"], ["columbus", "Help build a Jewish homeland"], ["columbus", "Hebrew with the vernacular"],
    ["columbus", "Judaism is the soul, Israel is the body"], ["columbus", "Keep Sabbath, festivals, inspiring customs"] ] },
  { title: "Jacobson or Hamburg Temple?", a: "jacobson", b: "hamburg", items: [
    ["jacobson", "Purpose: your religious education"], ["jacobson", "Why should we alone remain behind?"],
    ["jacobson", "Wore robes like a Protestant minister"], ["jacobson", "Not a rabbi, opened it in 1810"],
    ["hamburg", "Public worship neglected (nobody knows the language)"], ["hamburg", "German sermon and organ"],
    ["hamburg", "Confirmation for boys and girls"], ["hamburg", "Declared their city their Jerusalem"] ] },
];

// Short answers. pts = key points with keyword patterns for quick marking.
const SHORT = [
  { id: "s1", t: "conversion", q: "Compare Heine's and Mendelssohn's reasons for converting.",
    model: "Heine converted to get ahead in society; he saw the baptismal certificate as a ticket of admission to European culture and a job. Mendelssohn raised his children Christian because he saw Christianity as the religion of the most civilized people today, while Judaism had its day. Both were social or political reasons, not religious ones.",
    pts: [["Heine: ticket / career / get ahead", "ticket|career|job|position|university|doctor|get ahead|discriminat|accept"],
          ["Mendelssohn: creed of most civilized / Judaism had its day", "civiliz|had its day|reigning|now it is the christian|majority|times"],
          ["Both social/political, not religious", "social|political|not religious|secular|not because"]] },
  { id: "s2", t: "conversion", q: "Explain the quote: \"The baptismal certificate is the ticket of admission to European culture.\" Who said it and what does it mean?",
    model: "Heinrich Heine said it. He meant that for a Jew to be fully accepted in European society, get a career and avoid discrimination, he had to be baptized; it was a social move, not a religious belief.",
    pts: [["Names Heine", "heine"], ["Baptism/conversion = way into society", "society|accept|europe|in to|into|admission|career|job|discriminat"], ["Not religious belief", "not religious|social|political|didn.t believe|indifferen"]] },
  { id: "s3", t: "conversion", q: "How was conversion after emancipation different from conversion in the Middle Ages?",
    model: "In the Middle Ages (Crusades, Inquisition) Jews were forced to convert or be killed. After emancipation conversion was a free choice, and with religion playing a smaller role it became a secular, social and political act to be accepted in society.",
    pts: [["Middle Ages: forced", "forc|kill|inquisition|crusade|fear"], ["Now: choice", "choice|chose|choos|free"], ["Secular/social reasons", "secular|social|political|accept|career"]] },
  { id: "s4", t: "beginnings", q: "What was the original intent of the Reform movement according to Jacobson and the Hamburg Temple?",
    model: "Jacobson said his temple was for religious education, not to undermine the pillars of the faith. The Hamburg Temple said public worship was neglected because people no longer knew Hebrew, so they made it attractive and understandable (German sermon, organ, choir) to keep Jews from leaving or converting.",
    pts: [["Religious education / not undermine", "educat|undermine|pillar"], ["Worship neglected / nobody knows Hebrew", "neglect|language|hebrew|understand|meaningful|formula"], ["Keep Jews in, stop conversion / attractive", "keep|convert|attract|bring|access|come back"]] },
  { id: "s5", t: "beginnings", q: "Give two reasons the Reformers called their house of worship a \"temple\".",
    model: "First, \"temple\" sounded less foreign and less Jewish than synagogue, like the places of worship of other religions. Second, by using the name of the destroyed Temple in Jerusalem, they gave up hope of returning to Zion and declared Hamburg their Jerusalem: we are here to stay.",
    pts: [["Less foreign / less Jewish", "foreign|less jewish|other religion|church|buddhist|hindu|fit in|like them"], ["Gave up Jerusalem/Zion, here to stay", "jerusalem|zion|here to stay|restor|israel|return|hamburg"]] },
  { id: "s6", t: "beginnings", q: "List two changes the Hamburg Temple brought into Jewish worship and explain why.",
    model: "It added a German sermon and choir singing with an organ, and confirmation for both boys and girls. The goal was to make worship dignified, understandable and attractive, like their Christian neighbours, because people no longer understood Hebrew and stopped coming.",
    pts: [["Names a real change", "german sermon|sermon|organ|choir|confirm|girls"], ["Second change", "organ|choir|confirm|girls|sermon|german"], ["Why: attract / understand / like neighbours", "attract|understand|neglect|language|like the|christian|dignit|come"]] },
  { id: "s7", t: "issues", q: "Explain the debate between Frankel and Geiger at the Frankfurt conference.",
    model: "They argued whether Hebrew is needed in prayer. Frankel said Hebrew must prevail and be conserved because it is sacred to the whole people and prevents a schism. Geiger said a German prayer strikes a deeper chord because people understand it, and that Judaism is a religion, not a nation tied to one language.",
    pts: [["Topic: Hebrew vs vernacular in prayer", "hebrew|vernacular|language|german"], ["Frankel: conserve / sacred / unity", "conserv|sacred|schism|unit|keep"], ["Geiger: deeper chord / religion not nation", "deeper chord|understand|nation|religion"]] },
  { id: "s8", t: "issues", q: "Explain Geiger's line: \"the national aspect of Israel must recede into the background.\"",
    model: "In the preface to his new prayer book, Geiger said Judaism is only a religion, not a nation. So prayers about returning to Zion, a Jewish state in Palestine, rebuilding the Temple and the ingathering of exiles were removed, and prayers focused on hope for all mankind instead.",
    pts: [["Religion, not a nation", "religion|not a nation|nation"], ["Removed Zion / state / Temple / Messiah", "zion|palestine|state|temple|messiah|ingather|jerusalem|israel"], ["Prayer book / universal hope", "prayer|mankind|universal|all people|unif"]] },
  { id: "s9", t: "issues", q: "What were the three main issues in Geiger's preface to the Frankfurt prayer book?",
    model: "One: the connection to Israel and Zion is removed from prayer. Two: no more praying for the Messiah, rebuilding the Temple or the ingathering of exiles. Three: universalism, being open to other religions and hoping for the unification of all mankind instead of stressing Jewish separation.",
    pts: [["Israel / Zion", "israel|zion|palestine|state"], ["Messiah / Temple / ingathering", "messiah|temple|ingather|exile"], ["Universalism / other religions", "universal|other religion|mankind|open|separat"]] },
  { id: "s10", t: "evolution", q: "Describe the Pittsburgh Platform (1885). What did Classical Reform believe?",
    model: "It said Jews are no longer a nation but a religious community, so no return to Palestine. Only the moral laws are binding, and laws about diet, priestly purity and dress (like kashrut) don't fit modern life. Judaism is a progressive religion in accord with reason.",
    pts: [["Not a nation / no Palestine", "nation|palestine|zion|return"], ["Only moral laws / drop kashrut, dress", "moral|kashrut|kosher|diet|dress|ritual|ceremon"], ["Modern / progressive / reason", "modern|progress|reason|science"]] },
  { id: "s11", t: "evolution", q: "Why did the Reform movement change its views between 1885 and 1937?",
    model: "By 1937 the Nazis' Nuremberg Laws (1935) showed assimilation had failed: Jews were not accepted as Germans even if they converted, and Hitler went after them whether religion or nation. Zionism in Palestine was succeeding, so Reform brought back Jewish peoplehood and support for a homeland.",
    pts: [["Nazis / Nuremberg Laws / Hitler", "nazi|hitler|nuremberg|germany"], ["Assimilation failed / not accepted", "assimilat|accept|fail|convert"], ["Zionism success / homeland", "zion|homeland|palestine|israel"]] },
  { id: "s12", t: "evolution", q: "Compare the Pittsburgh and Columbus Platforms on Israel and on Hebrew.",
    model: "Pittsburgh (1885) said Jews are not a nation and expect no return to Palestine, and it drops rituals. Columbus (1937) says Judaism is the soul of which Israel is the body, asks all Jews to help build a Jewish homeland, and brings back Hebrew together with the vernacular.",
    pts: [["Pittsburgh: no nation / no Palestine", "pittsburgh|1885|no longer a nation|no return|not a nation"], ["Columbus: homeland / people", "columbus|1937|homeland|build|soul|body|people"], ["Hebrew returns", "hebrew"]] },
  { id: "s13", t: "evolution", q: "Is it right to say Reform Judaism is against Israel? Explain using the evolution of Reform.",
    model: "No. Early Reform (Geiger, Pittsburgh 1885) removed Zion and said Jews are not a nation. But the Columbus Platform (1937) changed this and called on all Jews to help build a Jewish homeland, and Reform today supports Israel.",
    pts: [["No / not today", "no\\b|not true|isn.t|wrong|not anti|false"], ["Early Reform rejected Zion", "early|pittsburgh|geiger|1885|nation|zion"], ["Columbus supports homeland", "columbus|1937|homeland|build|support"]] },
  { id: "s14", t: "evolution", q: "\"In view of the changes that have taken place in the modern world...\" Where is this from, and what is its significance?",
    model: "It is the opening of the Columbus Platform (1937). With the Nazis pushing Jews out of Germany and disaster coming, Reform had to rethink who it is, so it brought back Jewish peoplehood, Hebrew and support for a homeland in Palestine.",
    pts: [["Names Columbus", "columbus|1937"], ["Nazis / Holocaust / disaster", "nazi|holocaust|hitler|disaster|nuremberg|germany|persecut"], ["Rethink / change: peoplehood, Hebrew, homeland", "rethink|re-examin|chang|adapt|homeland|hebrew|people|palestine|israel|tradition"]] },
  { id: "s15", t: "evolution", q: "\"We accept as binding only the moral laws.\" Who said this and what does it mean?",
    model: "This is the Pittsburgh Platform (1885), Classical Reform. Only moral laws like \"don't kill\" must be followed, while ritual laws that make Jews different, like kashrut, Shabbat rules and dress, are dropped so Jews can be like their neighbours.",
    pts: [["Names Pittsburgh / Classical Reform", "pittsburgh|1885|classical"], ["Moral laws kept (e.g. don't kill)", "moral|kill|ethic|right and wrong"], ["Ritual laws dropped / be like others", "kosher|kashrut|ritual|shabbat|sabbath|dress|diet|like the|neighbo|church|christian|fit in"]] },
  { id: "s16", t: "issues", q: "\"The positive forms of Judaism are deeply rooted within its innermost being and must not be discarded coldly and heartlessly.\" Who said it and why?",
    model: "Zecharias Frankel said it at the Frankfurt conference. He argued the old forms, like praying in Hebrew, are part of Judaism's core, so they must be conserved to keep the Jewish people united and prevent a schism.",
    pts: [["Names Frankel", "frankel"], ["Keep tradition / Hebrew", "hebrew|tradition|keep|conserv|old"], ["Unity / prevent schism", "unit|schism|split|together|divid|people"]] },
];

// Dr. Polster's class on Oct 1, 2026 (day before the demo), from the class recording.
const CLASS_OCT1 = `DR. POLSTER'S CLASS, OCT 1 (the day before the demo). Teaching part of the recording, cleaned up.
DEMO FORMAT (his words): "I do the most recent stuff on the demo. So the stuff that we're doing today will be on the demo." 10 minutes (12.5 extra time). Page 1: five quotes, each with a blank, and a word bank at the bottom of "the people or the platform" ; one word per quote, one to one. You can use process of elimination. Example he gave: "The baptismal certificate is the ticket into European society" = Heinrich Heine ("this is on the demo, so I'm giving you one right here"). Page 2: three short answers, cross one out, write two sentences each for the other two. Example: give a quote, "tell me who said that and what's the significance of that." Maybe one conceptual or compare question. "If you focus on quotes, you'll be good." "You will be underwhelmed."
WHAT'S ON IT: Conversion (Heine vs Mendelssohn), Reform beginnings (Jacobson's little temple, the Hamburg Temple), Geiger vs Frankel, Geiger's prayer book, and today's Pittsburgh and Columbus Platforms.
JACOBSON (p. 14): know the first three indented lines: "What I had in mind when I first thought about building this temple was your religious education." All you need: he opened a temple and made it more reformed so more German Jews would want to come. "That's it."
HAMBURG TEMPLE (p. 15): the start of the constitution: "an ever decreasing knowledge of the language." Nobody knows Hebrew, nobody comes to shul, so make worship attractive and build it like the church nearby. The goal of early Reform was to attract Jews into their Jewish faith and identity, NOT to corrupt Judaism.
FRANKEL vs GEIGER (Frankfurt, pp. 17-18): Both agree there is no halakha that you must pray in Hebrew. Frankel, top left of p. 18: "The positive forms of Judaism are deeply rooted within its innermost being and must not be discarded coldly and heartlessly." ("That's a quote that could be on tomorrow.") Frankel: Hebrew connects us to our ancestors, it's uplifting. Geiger, right column: "A German prayer strikes a deeper chord than a Hebrew prayer": if you understand what you pray, it hits your soul; more Jews will understand. Frankel, middle of p. 18 ("literally this is the most important"): "It is necessary to conserve the things which are truly sacred to the entire people, to prevent any schism in Israel." If every Jew in the world prays in Hebrew, that keeps us together. Geiger, right column middle: "no member of this conference would wish to link Judaism to a particular nation." Geiger: Hebrew is to Jews what French is to France; he doesn't want a nation or a people, he wants a religion like Hinduism, Buddhism, Christianity. That defines Classical Reform.
GEIGER'S PRAYER BOOK (p. 23, "the most important part, underline, highlight"): "The national aspect of Israel must recede into the background." Practically: take out Israel, the ingathering of the exiles, returning to Jerusalem, rebuilding the Temple. Why: wanting to be somewhere else "puts a target on my head" and makes me different; "I'm a German, I'm here to stay," like the neighbours who go to their church. (The State of Israel only comes in 1948.) Sample short answer he gave 2.5/2.5: "Geiger said this in his new prayer book. He doesn't think Jewish national identity should be the focus; Judaism should mainly be a religion, so he gets rid of the connection to Israel and the return of the exiles."
TREIFA BANQUET (1883): two years before Pittsburgh, a party for about 300 people for graduating Reform rabbis served clams, shrimp salad and shellfish (no pork). Significance: being like everyone else means losing what makes you Jewish.
PITTSBURGH PLATFORM (p. 24, 1885) = CLASSICAL REFORM, a "platform of principles: this is what we stand for." Most liberal point. "This is not Reform Judaism today." Quotes to know: (1) bottom of p. 24, third principle: "we accept as binding only the moral laws, and maintain only such ceremonies as elevate and sanctify our lives, but reject all such as are not adapted to the views and habits of modern civilization." Moral law = don't kill. Drop the legal/ritual laws unique to Jews (kosher, Shabbat, bris): "the church down the street ain't doing that." (2) "We consider ourselves no longer a nation, but a religious community": reject the return to Israel, "we're here to stay," not the chosen people, not a light unto the nations. Sixth principle (Judaism a progressive religion; Christianity and Islam daughter religions): "We're a religion like other religions." He said don't worry about the Messiah or other-religions parts. Why all this: we're losing Jews to conversion, so make Judaism attractive by being like the neighbours.
THE PENDULUM: Frankel (tradition, Hebrew, conserve) → Geiger (German, a religion not a nation, more liberal) → Pittsburgh (most liberal) → Columbus 1937: the pendulum swings back, Reform "re-reforms" and becomes more traditional (moves toward Frankel, not all the way). Reform today is even more traditional (revised again in 1999).
COLUMBUS PLATFORM (p. 26, 1937): Jews being pushed out of Germany, a sense of coming disaster (not yet the Holocaust). Quote to know, middle of p. 26, the opening: "In view of the changes that have taken place in the modern world..." = Columbus, a response to the coming disaster: we have to rethink who we are. Answer he accepted for full marks: as the world changes, Judaism needs to adapt and rethink itself. ("Each age has the obligation to adapt the teachings of the Torah" shows some laws can come back, but "I will not ask you this one.") Quote to know, middle of p. 27, number 5 (Israel): "We affirm the obligation of all Jewry to aid in its upbuilding as a Jewish homeland by endeavoring to make it not only a haven of refuge for the oppressed but also a center of Jewish culture and spiritual life." Israel comes back into prayer and into Reform's principles: "Judaism is the soul of which Israel is the body." Hebrew comes back too.
SUMMARY IN ONE LINE (his): think of it as language. Frankel: Hebrew, Hebrew, conserve. Geiger: German, German, it strikes a chord. Pittsburgh adopts that. 1937 Columbus: "Wait, we have to re-reform," put Hebrew and Israel back in.`;
